use lynx if available

diff --git a/Management/psrchive_install b/Management/psrchive_install
--- a/Management/psrchive_install
+++ b/Management/psrchive_install
@@ -1,4 +1,4 @@
-#!/bin/csh -fe
+#!/bin/csh -f
 
 if ( "$1" == "" || "$1" == "-h" || "$1" == "--help" ) then
   echo
@@ -32,10 +32,28 @@ if (-d $installation_path/bin) then
   exit
 endif
 
-mkdir -p $installation_path/src
+
+# program to be used to download source code
+#
+
+if ( `which curl` != "" ) set psrchive_download = curl
+if ( `which lynx` != "" ) set psrchive_download = lynx
+
+if ( ! $?psrchive_download ) then
+  echo
+  echo "psrchive_install: no suitable download program (curl or lynx)"
+  echo
+  exit -1
+endif
+
+
+# make the path to which the source code will be downloaded
+#
+mkdir -fp $installation_path/src
 cd $installation_path/src
 
 echo "Will install psrchive $1 in $installation_path"
+
 
 # name of the sourcecode distribution file
 #
@@ -46,15 +64,24 @@ set tarfile=psrchive-$1.tar.gz
 #
 set sourceforge=http://downloads.sourceforge.net
 
+echo -n "Downloading $tarfile from sourceforge "
 
-# curl options used:
-#   -L  follow any mirror location specified by the server
-#   -f  fail silently
-#   -O  write to file named like remote file
-#
-echo "Downloading $tarfile from sourceforge ..."
-curl --connect-timeout 30 -f -L -O $sourceforge/psrchive/$tarfile
+if ( $psrchive_download == "curl" ) then
+  # curl options used:
+  #   -L  follow any mirror location specified by the server
+  #   -f  fail silently
+  #   -O  write to file named like remote file
 
+  echo "using curl ..."
+  curl --connect-timeout 30 -f -L -O $sourceforge/psrchive/$tarfile
+endif
+
+if ( $psrchive_download == "lynx" ) then
+  echo "using lynx ..."
+  lynx -dump $sourceforge/psrchive/$tarfile > $tarfile
+endif
+
+if ( $status != 0 ) exit -1
 
 echo "Unpacking $tarfile ..."
 gunzip -c $tarfile | tar xf -
@@ -67,11 +94,17 @@ cd psrchive-$1
 echo "Compiling ..."
 make
 
+if ( $status != 0 ) exit -1
+
 echo "Checking ..."
 make check
 
+if ( $status != 0 ) exit -1
+
 echo "Installing ..."
 make install
+
+if ( $status != 0 ) exit -1
 
 echo "Setting permissions ..."
 
